# Generated by Django 4.2.4 on 2023-09-04 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_trainerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('name', models.CharField(max_length=100)),
                ('sets', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FitnessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('description', models.CharField(max_length=200)),
                ('exercises', models.ManyToManyField(to='server.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trainerprofile',
            name='specialization',
            field=models.CharField(choices=[('Yoga', 'Yoga'), ('Strength Training', 'Strength Training'), ('Cardio', 'Cardio'), ('Pilates', 'Pilates'), ('CrossFit', 'CrossFit'), ('Dance', 'Dance'), ('Functional Training', 'Functional Training'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('goal', models.CharField(max_length=50)),
                ('duration', models.PositiveIntegerField()),
                ('fitness_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.fitnessplan')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='subscribed_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
