# Generated by Django 4.2.4 on 2023-09-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_exercise_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
